[phases.setup]
nixpkgsArchive = "23.05"

[phases.install]
cmds = ["composer install --no-interaction --prefer-dist --optimize-autoloader"]

[phases.build]
cmds = ["php artisan migrate --force", "php artisan config:cache"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
